server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ${packageName}.entity

logging:
  level:
    root: INFO
    ${packageName}: DEBUG

